create sequence hibernate_sequence start 1 increment 1;

create table books (id int8 generated by default as identity,
                    book_text varchar(255) not null ,
                    img_name varchar(255),
                    name varchar(255) not null ,
                    user_id int8,
                    primary key (id));

create table users (id int8 generated by default as identity,
                    email varchar(255) not null unique,
                    firstname varchar(255) not null ,
                    lastname varchar(255) not null ,
                    password varchar(255) not null ,
                    role varchar(255) default 'USER' not null,
                    status varchar(255) default 'ACTIVE' not null,
                    primary key (id));

alter table if exists books add constraint book_user_fk foreign key (user_id) references users